---

product: fahcontrol

url: https://download.foldingathome.org/releases
beta: beta/release/{{ product }}
public: public/release/{{ product }}

fah_control_pkgs:
  Debian:
    '7.6.1': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.1-1_all.deb'
    '7.6.2': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.2-1_all.deb'
    '7.6.3': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.3-1_all.deb'
    '7.6.4': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.4-1_all.deb'
    '7.6.5': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.5-1_all.deb'
    '7.6.6': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.6-1_all.deb'
    '7.6.7': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.7-1_all.deb'
    '7.6.8': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.8-1_all.deb'
    '7.6.9': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.9-1_all.deb'
    '7.6.10': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.10-1_all.deb'
    '7.6.11': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.11-1_all.deb'
    '7.6.12': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.12-1_all.deb'
    '7.6.13': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.13-1_all.deb'
    '7.6.21': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.21-1_all.deb'
    'latestbeta': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/latest_all.deb'
    'latestpublic': '{{ url }}/{{ public }}/debian-stable-64bit/v7.6/latest_all.deb'

  Ubuntu:
    '7.5.0': '{{ url }}/{{ public }}/debian-stable-64bit/v7.5/{{ product }}_7.5.0-1_all.deb'
    '7.5.1': '{{ url }}/{{ public }}/debian-stable-64bit/v7.5/{{ product }}_7.5.1-1_all.deb'
    '7.6.0': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.0-1_all.deb'
    '7.6.1': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.1-1_all.deb'
    '7.6.2': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.2-1_all.deb'
    '7.6.3': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.3-1_all.deb'
    '7.6.4': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.4-1_all.deb'
    '7.6.5': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.5-1_all.deb'
    '7.6.6': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.6-1_all.deb'
    '7.6.7': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.7-1_all.deb'
    '7.6.8': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.8-1_all.deb'
    '7.6.9': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.9-1_all.deb'
    '7.6.10': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.10-1_all.deb'
    '7.6.11': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.11-1_all.deb'
    '7.6.12': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.12-1_all.deb'
    '7.6.13': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.13-1_all.deb'
    '7.6.21': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.21-1_all.deb'
    'latestbeta': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/latest_all.deb'
    'latestpublic': '{{ url }}/{{ public }}/debian-stable-64bit/v7.6/latest_all.deb'

  Fedora:
    '7.4.15': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.4.15-1.noarch.rpm'
    '7.4.16': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.4.16-1.noarch.rpm'
    '7.4.17': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.4.17-1.noarch.rpm'
    '7.4.18': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.4.18-1.noarch.rpm'
    '7.5.0':  '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.5.0-1.noarch.rpm'
    '7.5.1':  '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.5.1-1.noarch.rpm'
    '7.6.0':  '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.0-1.noarch.rpm'
    '7.6.1':  '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.1-1.noarch.rpm'
    '7.6.2':  '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.2-1.noarch.rpm'
    '7.6.3':  '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.3-1.noarch.rpm'
    '7.6.4':  '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.4-1.noarch.rpm'
    '7.6.5':  '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.5-1.noarch.rpm'
    '7.6.6':  '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.6-1.noarch.rpm'
    '7.6.7':  '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.7-1.noarch.rpm'
    '7.6.8':  '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.8-1.noarch.rpm'
    '7.6.9':  '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.9-1.noarch.rpm'
    '7.6.10': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.10-1.noarch.rpm'
    '7.6.11': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.11-1.noarch.rpm'
    '7.6.12': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.12-1.noarch.rpm'
    '7.6.13': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.13-1.noarch.rpm'
    'latestpublic': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/latest.noarch.rpm'
    'latestbeta':  '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/latest.noarch.rpm'

  RedHat:
    '7.4.15': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.4.15-1.noarch.rpm'
    '7.4.16': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.4.16-1.noarch.rpm'
    '7.4.17': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.4.17-1.noarch.rpm'
    '7.4.18': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.4.18-1.noarch.rpm'
    '7.5.0':  '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.5.0-1.noarch.rpm'
    '7.5.1':  '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.5.1-1.noarch.rpm'
    '7.6.0':  '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.0-1.noarch.rpm'
    '7.6.1':  '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.1-1.noarch.rpm'
    '7.6.2':  '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.2-1.noarch.rpm'
    '7.6.3':  '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.3-1.noarch.rpm'
    '7.6.4':  '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.4-1.noarch.rpm'
    '7.6.5':  '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.5-1.noarch.rpm'
    '7.6.6':  '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.6-1.noarch.rpm'
    '7.6.7':  '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.7-1.noarch.rpm'
    '7.6.8':  '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.8-1.noarch.rpm'
    '7.6.9':  '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.9-1.noarch.rpm'
    '7.6.10': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.10-1.noarch.rpm'
    '7.6.11': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.11-1.noarch.rpm'
    '7.6.12': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.12-1.noarch.rpm'
    '7.6.13': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.13-1.noarch.rpm'
    '7.6.21': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.21-1.noarch.rpm'
    'latestpublic': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/latest.noarch.rpm'
    'latestbeta':  '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/latest.noarch.rpm'

  CentOS:
    '7.4.15': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.4.15-1.noarch.rpm'
    '7.4.16': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.4.16-1.noarch.rpm'
    '7.4.17': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.4.17-1.noarch.rpm'
    '7.4.18': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.4.18-1.noarch.rpm'
    '7.5.0':  '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.5.0-1.noarch.rpm'
    '7.5.1':  '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.5.1-1.noarch.rpm'
    '7.6.0':  '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.0-1.noarch.rpm'
    '7.6.1':  '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.1-1.noarch.rpm'
    '7.6.2':  '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.2-1.noarch.rpm'
    '7.6.3':  '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.3-1.noarch.rpm'
    '7.6.4':  '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.4-1.noarch.rpm'
    '7.6.5':  '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.5-1.noarch.rpm'
    '7.6.6':  '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.6-1.noarch.rpm'
    '7.6.7':  '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.7-1.noarch.rpm'
    '7.6.8':  '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.8-1.noarch.rpm'
    '7.6.9':  '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.9-1.noarch.rpm'
    '7.6.10': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.10-1.noarch.rpm'
    '7.6.11': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.11-1.noarch.rpm'
    '7.6.12': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.12-1.noarch.rpm'
    '7.6.13': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.13-1.noarch.rpm'
    '7.6.21': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.21-1.noarch.rpm'
    'latestpublic': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/latest.noarch.rpm'
    'latestbeta':  '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/latest.noarch.rpm'

  Amazon:
    '7.4.15': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.4.15-1.noarch.rpm'
    '7.4.16': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.4.16-1.noarch.rpm'
    '7.4.17': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.4.17-1.noarch.rpm'
    '7.4.18': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.4.18-1.noarch.rpm'
    '7.5.0':  '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.5.0-1.noarch.rpm'
    '7.5.1':  '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.5.1-1.noarch.rpm'
    '7.6.0':  '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.0-1.noarch.rpm'
    '7.6.1':  '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.1-1.noarch.rpm'
    '7.6.2':  '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.2-1.noarch.rpm'
    '7.6.3':  '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.3-1.noarch.rpm'
    '7.6.4':  '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.4-1.noarch.rpm'
    '7.6.5':  '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.5-1.noarch.rpm'
    '7.6.6':  '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.6-1.noarch.rpm'
    '7.6.7':  '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.7-1.noarch.rpm'
    '7.6.8':  '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.8-1.noarch.rpm'
    '7.6.9':  '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.9-1.noarch.rpm'
    '7.6.10': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.10-1.noarch.rpm'
    '7.6.11': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.11-1.noarch.rpm'
    '7.6.12': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.12-1.noarch.rpm'
    '7.6.13': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.13-1.noarch.rpm'
    '7.6.21': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.21-1.noarch.rpm'
    'latestpublic': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/latest.noarch.rpm'
    'latestbeta':  '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/latest.noarch.rpm'
