---
# Tasks for configuring Supervisord.
- import_tasks: dependencies.yaml

# TODO: How to run cpu or gpu tasks based on single tag present or not??
#- import_tasks: cpu_only.yaml  

#- import_tasks: gpu.yaml
#  tags: gpu
  

